stages:
  - build
  - deploy

build:
  stage: build
  image: node:latest
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - docker build -t $IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG
  tags:
    - local
  only:
    - master

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl
    entrypoint:
      - ""
  environment:
    name: production
    kubernetes:
      namespace: aaron
  variables:
    KUBE_NAMESPACE: aaron
  script:
    - kubectl apply -f ./k8s/docs-deployment.yaml
    - kubectl apply -f ./k8s/docs-ingress.yaml
    - kubectl rollout restart deployment docs
