backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: assets/img/uploads

collections:
  - name: docs
    label: Docs
    folder: docs
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Label, widget: string }
      - { name: body, label: Body, widget: markdown }
