backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: assets/img/uploads

collections:
  - name: docs_chaster
    label: Docs - Chaster
    label_singular: Docs - Chaster
    folder: docs
    preview_path: '{{slug}}'
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar label, widget: string }
      - { name: body, label: Body, widget: markdown }
  - name: docs_locks
    label: Docs - Locks
    label_singular: Docs - Locks
    folder: docs/locks
    preview_path: 'locks/{{slug}}'
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar label, widget: string }
      - { name: body, label: Body, widget: markdown }
  - name: docs_features
    label: Docs - Features
    label_singular: Docs - Features
    folder: docs/features
    preview_path: 'features/{{slug}}'
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar label, widget: string }
      - { name: body, label: Body, widget: markdown }
  - name: docs_activity
    label: Docs - Activity
    label_singular: Docs - Activity
    folder: docs/activity
    preview_path: 'activity/{{slug}}'
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar label, widget: string }
      - { name: body, label: Body, widget: markdown }
  - name: docs_extensions
    label: Docs - Extensions
    label_singular: Docs - Extensions
    folder: docs/extensions
    preview_path: 'extensions/{{slug}}'
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar label, widget: string }
      - { name: body, label: Body, widget: markdown }
