backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: assets/img/uploads

collections:
  - name: docs
    label: Docs
    label_singular: Doc
    folder: docs
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - name: title
        label: Title
        widget: string
      - name: sidebar_label
        label: Label
        widget: string
      - name: body
        label: Body
        widget: markdown
    nested:
      depth: 3
      summary: '{{title}}'
    meta: 
      path:
        widget: string
        label: Path
        index_file: index
  - name: settings
    label: Settings
    files:
      - name: sidebar
        label: Sidebar
        file: sidebars.json
        fields:
          - label: Content
            name: body
            widget: text
